health: redme

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -2,6 +2,7 @@
 set -eo pipefail
 
 declare USE_SSH=0
+declare APP_NAME_SUPPORTED=1
 #Set branch to master unless specified by the user
 declare -x TV_BRANCH="${TV_BRANCH:-"main"}"
 declare -xr TV_REMOTE="${TV_REMOTE:-quantumfate/TestVim.git}"
@@ -9,12 +10,12 @@ declare -xr XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"
 declare NVIM_APPNAME="tvim"
 
 function check_neovim_min_version() {
-    local verify_version_cmd='if !has("nvim-0.8") | cquit | else | quit | endif'
+    local verify_version_cmd='if !has("nvim-0.9") | cquit | else | quit | endif'
 
     # exit with an error if min_version not found
     if ! nvim --headless -u NONE -c "$verify_version_cmd"; then
-        echo "[ERROR]: TestVim requires at least Neovim v0.8 or higher"
-        exit 1
+        echo "[WARN]: Neovim v0.9 not satisfied. Appname defaults to 'nvim'."
+        APP_NAME_SUPPORTED=0
     fi
 }
 
@@ -89,6 +90,20 @@ function __backup_dir() {
 }
 
 function clone_tvim() {
+
+    # Check if there's an existing Neovim configuration
+    if [ -d "$XDG_CONFIG_HOME/$NVIM_APPNAME" ]; then
+        echo "An existing Neovim configuration was found in $XDG_CONFIG_HOME/$NVIM_APPNAME."
+        echo "Would you like to backup and replace it? (y/n)"
+        read -r answer
+
+        if [[ "$answer" != "y" ]]; then
+            echo "Aborting installation."
+            exit 1
+        else
+            __backup_dir "$XDG_CONFIG_HOME/$NVIM_APPNAME"
+        fi
+    fi
     msg "Cloning TestVim configuration"
 
     if [ "$USE_SSH" -eq 0 ]; then
@@ -116,7 +131,13 @@ function setup_tvim() {
 
     if [ -d "$HOME/.local/bin" ]; then
         ln -s "$XDG_CONFIG_HOME/$NVIM_APPNAME/scripts/tvim" "$HOME/.local/bin/tvim"
-        tvim --headless -c 'quitall'
+        # if appname supported
+        if [ "$APP_NAME_SUPPORTED" -eq 1 ]; then
+            tvim --headless -c 'quitall'
+        else
+            tvim --appname 'nvim' --headless -c 'quitall'
+        fi
+
     else
         msg "Manually link the tvim script to your path"
     fi
diff --git a/scripts/tvim b/scripts/tvim
--- a/scripts/tvim
+++ b/scripts/tvim
@@ -8,12 +8,13 @@ testing=false
 test_file="minimal_init.lua"
 appname="tvim"
 clear_instance=false
+freeze=false
 
 print_usage() {
     printf "Run a neovim instance with the specified configuration. The Neovim XDG directories are set to temporary directories which are persisted between runs\n"
-    printf "unless the -p flag is set. In this case the default Neovim XDG directories appended with the appname are used.\n"
+    printf "unless the --persist flag is set. In this case, the default Neovim XDG directories appended with the appname are used.\n"
     printf "\nPlenary and structlog are cloned into the packpath if they don't exist yet and will always be in the runtime path.\n"
-    printf "\nUsage: %s [-a appname] [-i init_file] [--testing] [-t test_file] [-x test_arg] [-c] [-p]\n" "$0"
+    printf "\nUsage: %s [-a appname] [-i init_file] [--testing] [-t test_file] [-x test_arg] [-c] [-p] [--freeze]\n" "$0"
     printf "\nOptions:\n"
     printf "  -a, --appname APPNAME       Specify the appname to use. Default is 'tvim'. (Optional)\n"
     printf "  -I, --init-file FILENAME    Specify the init file to use. Default is 'init.lua'. (Optional)\n"
@@ -21,8 +22,9 @@ print_usage() {
     printf "  -t, --test-file FILENAME    Specify the test file to use. Only valid when --testing is set. Default is 'minimal_init.lua'. (Optional)\n"
     printf "  -x, --test-arg ARG          Specify an argument for the plenary busted lua call. Only valid when --testing is set. (Optional)\n"
     printf "  -r, --remove                Force the script start with a fresh instance of neovim. This will remove the reference to the last /tmp folder\n"
-    printf "                              or removes the persisted folders when --persist is set. Consider setting the appname explicitely when you used a different appname before (Optional)\n"
+    printf "                              or removes the persisted folders when --persist is set. Consider setting the appname explicitly when you used a different appname before (Optional)\n"
     printf "  --persist                   Use default Neovim's standard user directories instead of temporary directories. (Optional)\n"
+    printf "  --freeze                    Copy all files from the /tmp/XDG directories to the real XDG directories. Not to be used with --persist. (Optional)\n"
     printf "  -h, --help                  Show this help message and exit.\n"
 }
 
@@ -45,6 +47,10 @@ while (( "$#" )); do
                 echo "Error: Argument for $1 is missing" >&2
                 exit 1
             fi
+            ;;
+        --freeze)
+            freeze=true
+            shift
             ;;
         --testing)
             testing=true
@@ -97,6 +103,11 @@ while (( "$#" )); do
     esac
 done
 
+if [ "$freeze" = true ] && [ "$persisting" = true ]; then
+    echo "Error: --freeze and --persist modes are mutually exclusive."
+    exit 1
+fi
+
 if [ "$clear_instance" = true ]; then
     if [ -f /tmp/testnvim/vars.sh ]; then
         rm -f /tmp/testnvim/vars.sh
@@ -108,7 +119,6 @@ if [ "$clear_instance" = true ]; then
     fi
 fi
 
-# if not persisting
 if [ "$persisting" = false ]; then
     if [ -f /tmp/testnvim/vars.sh ]; then
         source /tmp/testnvim/vars.sh
@@ -121,7 +131,6 @@ if [ "$persisting" = false ]; then
         echo "export TESTNVIM_CACHE_DIR=$TESTNVIM_CACHE_DIR" > /tmp/testnvim/vars.sh
         echo "export TESTNVIM_STATE_DIR=$TESTNVIM_STATE_DIR" >> /tmp/testnvim/vars.sh
         echo "export TESTNVIM_DATA_DIR=$TESTNVIM_DATA_DIR" >> /tmp/testnvim/vars.sh
-
     fi
 fi
 
@@ -133,6 +142,31 @@ export XDG_CACHE_HOME="${TESTNVIM_CACHE_DIR:-"$HOME/.cache"}"
 export NVIM_APPNAME="$appname"
 
 declare -xr TESTNVIM_CONFIG_DIR XDG_STATE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_CACHE_HOME NVIM_APPNAME
+
+function freeze_config() {
+    # Check if there's any existing directory in the real XDG directories
+    if [ -d "$HOME/.local/state/$appname" ] || [ -d "$HOME/.local/share/$appname" ] || [ -d "$HOME/.cache/$appname" ]; then
+        echo "Existing directories found in the real XDG directories."
+        echo "Would you like to backup and replace them? (y/n)"
+        read -r answer
+
+        if [[ "$answer" != "y" ]]; then
+            echo "Aborting freeze."
+            exit 1
+        else
+            __backup_dir "$HOME/.local/state/$appname"
+            __backup_dir "$HOME/.local/share/$appname"
+            __backup_dir "$HOME/.cache/$appname"
+        fi
+    fi
+
+    # Copy the files from /tmp/XDG_whatever to the real XDG directories
+    echo "Freezing configuration..."
+    cp -r "$TESTNVIM_STATE_DIR/." "$HOME/.local/state/$appname/"
+    cp -r "$TESTNVIM_DATA_DIR/." "$HOME/.local/share/$appname/"
+    cp -r "$TESTNVIM_CACHE_DIR/." "$HOME/.cache/$appname/"
+    echo "Freeze complete."
+}
 
 echo "appname: $NVIM_APPNAME"
 echo "cache dir: $XDG_CACHE_HOME"
@@ -157,7 +191,7 @@ function test_nvim() {
     nvim -u "${XDG_CONFIG_HOME}/${NVIM_APPNAME}/tests/minimal_init.lua" \
         --cmd "set runtimepath+=${XDG_STATE_HOME}/${NVIM_APPNAME}/after/pack/lazy/opt/plenary" \
         --cmd "set runtimepath+=${XDG_STATE_HOME}/${NVIM_APPNAME}/after/pack/lazy/opt/structlog" \
-        $PARAMS
+        "$@" $PARAMS
 }
 
 function run_nvim() {
@@ -169,6 +203,11 @@ function run_nvim() {
 }
 
 function setup() {
+    if [ "$freeze" = true ]; then
+        freeze_config
+        exit 0
+    fi
+
     if [ "$testing" = true ]; then
         if [ -n "$test_arg" ]; then
             test_nvim --headless -c "lua require('plenary.busted').run('$test_arg')"
